# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # aliased to a recent 5.6.x version
  - '5.6'
  - '7.1'

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=pgsql

# optionally set up exclutions and allowed failures in the matrix

# execute any number of scripts before the test run, custom env's are available as variables

before_script:
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl
  - sudo /etc/init.d/apache2 restart
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "wget http://selenium-release.storage.googleapis.com/3.7/selenium-server-standalone-3.7.1.jar"
  - sleep 10
  - "java -jar selenium-server-standalone-3.7.1.jar -enablePassThrough false  > /dev/null &"
  - sleep 5
  - "wget https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip && unzip chromedriver_linux64.zip && sudo mv chromedriver /usr/bin"
  - composer update


addons:
  chrome: stable
before_install:
  - composer self-update
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &


# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script:
  - vendor/behat/behat/bin/behat
# configure notifications (email, IRC, campfire etc)
after_success:
    - bash <(curl -s https://codecov.io/bash)
